name: Hello world
on: [push]

jobs: #pipeline
  job1: #pipeline1
    runs-on: ubuntu-latest
    steps: #stages
      - name: step1
        uses: echo "Hello World"
      - name: step2
        uses: echo "Hello Github Action"
